FROM public.ecr.aws/docker/library/python:3.12-alpine

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir --disable-pip-version-check boto3

COPY init_dynamodb.py .

RUN chmod +x init_dynamodb.py

CMD ["python", "init_dynamodb.py"]
