name: Web CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/web-pipeline.yml'
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/web-pipeline.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ./frontend/.nvmrc

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit

      - name: Unit Tests
        run: npm run test:web -- --ci --bail --run-in-band --coverage --color

      - name: Build
        run: npm run build:web

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: web-build
          path: frontend/www/web
          if-no-files-found: error

      - name: Upload web coverage report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: web-coverage-report
          path: frontend/coverage

  deploy-dev:
    needs: build
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: web-build
          path: frontend/www/web

      - name: Replace environment variables
        uses: cschleiden/replace-tokens@v1.3
        with:
          files: '["frontend/www/**/*.js"]'
        env:
          APP_API_URL: ${{ vars.APP_API_URL }}
          APP_COGNITO_USER_POOL_ID: ${{ vars.APP_COGNITO_USER_POOL_ID }}
          APP_COGNITO_USER_POOL_CLIENT_ID: ${{ vars.APP_COGNITO_USER_POOL_CLIENT_ID }}
          APP_COGNITO_DOMAIN: ${{ vars.APP_COGNITO_DOMAIN }}
          APP_COGNITO_REDIRECT_URLS: ${{ vars.APP_COGNITO_REDIRECT_URLS }}
          APP_CLIENT_MICROSERVICE_URL: ${{ vars.APP_CLIENT_MICROSERVICE_URL }}
          APP_VENDOR_MICROSERVICE_URL: ${{ vars.APP_VENDOR_MICROSERVICE_URL }}
          APP_PROVIDER_MICROSERVICE_URL: ${{ vars.APP_PROVIDER_MICROSERVICE_URL }}
          APP_PRODUCT_MICROSERVICE_URL: ${{ vars.APP_PRODUCT_MICROSERVICE_URL }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ vars.AWS_ROLE_SESSION_NAME }}

      - name: Sync to S3 (dev)
        run: aws s3 sync frontend/www/web/ s3://${{ secrets.S3_WEB_BUCKET }} --delete

      - name: Invalidate CloudFront (dev)
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

  e2e-dev:
    needs: deploy-dev
    if: github.ref == 'refs/heads/develop'
    timeout-minutes: 60
    environment: dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ./frontend/.nvmrc

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps --only-shell

      - name: Run Playwright tests
        run: npx playwright test
        env:
          PLAYWRIGHT_BASE_URL: ${{ vars.PLAYWRIGHT_BASE_URL }}

      - uses: actions/upload-artifact@v4
        name: Upload E2E Test Report
        if: ${{ !cancelled() }}
        with:
          name: web-e2e-report
          path: frontend/playwright-report/
          retention-days: 30

  deploy-prod:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: web-build
          path: frontend/www/web

      - name: Replace environment variables
        uses: cschleiden/replace-tokens@v1.3
        with:
          files: '["frontend/www/**/*.js"]'
        env:
          APP_API_URL: ${{ vars.APP_API_URL }}
          APP_COGNITO_USER_POOL_ID: ${{ vars.APP_COGNITO_USER_POOL_ID }}
          APP_COGNITO_USER_POOL_CLIENT_ID: ${{ vars.APP_COGNITO_USER_POOL_CLIENT_ID }}
          APP_COGNITO_DOMAIN: ${{ vars.APP_COGNITO_DOMAIN }}
          APP_COGNITO_REDIRECT_URLS: ${{ vars.APP_COGNITO_REDIRECT_URLS }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ vars.AWS_ROLE_SESSION_NAME }}

      - name: Sync to S3 (prod)
        run: aws s3 sync frontend/www/web/ s3://${{ secrets.S3_WEB_BUCKET }} --delete

      - name: Invalidate CloudFront (prod)
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
