name: Web CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/web-pipeline.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ./frontend/.nvmrc

      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit

      - name: Unit Tests
        run: npm run test -- web --ci --bail --run-in-band --coverage --color

      - name: Build
        run: npm run build:web

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: frontend/www/web
